# Generated by Django 2.1.7 on 2019-03-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fibonacci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latency', models.CharField(blank=True, max_length=100, null=True)),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('result', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
